# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rgb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('red', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
            ],
        ),
    ]
